### ISSUE TITLE
Task US02 - Histórias

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#100]
# Task US02 - Histórias
---
### Descrição:
Nessa task, necessária para completar a US02, o desenvolvedor deve criar as histórias para treinamento do chatbot.

### Critérios de Aceitação
- [ ] As histórias devem ser adequadas aos intents criados
- [ ] As histórias devem ser elaboradas em português
- [ ] As histórias devem responder as perguntas com a informação correta

**Comment by Mexazonic** [comment]
<a href="https://github.com/pylearner-bot/pylearner-rasa/tree/US02-Importacao-Dados-JSON/bot/data/stories">Stories</a> finalizadas.

**Comment by davialvb** [comment]
Arrume a formatação do MD!
