### ISSUE TITLE
Task US04 - Histórias

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#101]
# Task US04 - Histórias
---
### Descrição:
Nessa task, necessária para completar a US04, o desenvolvedor deve criar as histórias para treinamento do chatbot.

### Critérios de Aceitação
- [x] As histórias devem ser adequadas aos intents criados
- [x] As histórias devem ser elaboradas em português
- [x] As histórias devem responder as perguntas com a informação correta

**Comment by Eugeniosales** [comment]
Estórias criadas e prontas para a revisão. [Estórias](https://github.com/pylearner-bot/pylearner-rasa/blob/US-04-dados-faltantes/bot/data/stories/missing_data.md)

**Comment by davialvb** [comment]
Arrume a formatação do MD!

**Comment by Eugeniosales** [comment]
Arrumado.
