### ISSUE TITLE
Task US14 - Histórias

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#102]
# Task US14 - Histórias
---
### Descrição:
Nessa task, necessária para completar a US14, o desenvolvedor deve criar as histórias para treinamento do chatbot.

### Critérios de Aceitação
- [ ] As histórias devem ser adequadas aos intents criados
- [ ] As histórias devem ser elaboradas em português
- [ ] As histórias devem responder as perguntas com a informação correta
