### ISSUE TITLE
Task US15 - Histórias

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#103]
# Task US15 - Histórias
---
### Descrição:
Nessa task, necessária para completar a US15, o desenvolvedor deve criar as histórias para treinamento do chatbot.

### Critérios de Aceitação
- [x] As histórias devem ser adequadas aos intents criados
- [x] As histórias devem ser elaboradas em português
- [x] As histórias devem responder as perguntas com a informação correta

**Comment by joao15victor08** [comment]
[Stories](https://github.com/pylearner-bot/pylearner-rasa/blob/US15-histograma-features/bot/data/stories/histogram.md) finalizadas e colocados em review.

**Comment by davialvb** [comment]
Arrume a formatação do MD!
