### ISSUE TITLE
EP03 - Aprendizado Supervisionado

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#105]
# EP03 - Aprendizado Supervisionado
---
### Descrição:
Neste épico serão incluídos temas os quais, estão incluídos dentro da categoria de aprendizado supervisionado em aprendizado de máquina. Dentre estes tópicos estão incluídas as classificações, dividas em métricas e modelos, assim como as regressões, onde são incluídas assim como nas classificações, as regras e os modelos.

Ao ser concluído, este épico disponibilizará no bot, a possibilidade de tirar dúvidas sobre aprendizado supervisionado para machine learning.

### Histórias de Usuário
- [ ] US07 - Eu como usuário desejo saber quais métricas usar para classificação
- [ ] US08 - Eu como usuário desejo saber quais modelos usar para classificação
- [ ] US09 - Eu como usuário desejo saber quais métricas usar para regressão
- [ ] US10 - Eu como usuário desejo saber quais modelos usar para regressão
