### ISSUE TITLE
EP04 - Aprendizado não supervisionado

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#106]
# EP04 - Aprendizado não supervisionado
---
### Descrição:
Neste épico serão incluídos temas os quais, estão incluídos dentro da categoria de aprendizado supervisionado em aprendizado de máquina. Dentre estes tópicos está incluída a clusterização KMeans, o mapa Kohonem e um modelo Hidden Markok.

Ao ser concluído, este épico disponibilizará no bot, a possibilidade de tirar dúvidas sobre aprendizado supervisionado para machine learning.

### Histórias de Usuário
- [x] US11 - Eu como usuário desejo saber como fazer um clust KMeans
- [ ] US12 - Eu como usuário desejo saber como fazer um mapa Kohonen
- [ ] US13 - Eu como usuário desejo saber como fazer um Hidden Markov
