### ISSUE TITLE
EP08 - Tutoriais

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#119]
### Descrição:
Este épico consiste nas em tudo relacionado às interações entre bot e usuário que não dizem respeito a informações técnicas. 

Ao ser concluído, este épico disponibilizará no bot, a possibilidade do usuário e do bot interagirem entre si, por meio de conversa.

### Histórias de Usuário
- [x] US19 - Tutorial Machine Learning do Problema Iris Flower
- [x] US 20 - Tutorial Machine Learning do Problema do Titanic
- [x] US21 - Tutorial Machine Learning do Problema MINIST
