### ISSUE TITLE
Finalizar Documento de Visão

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#42]
### Objetivo
Esta issue corresponde à issue de finalização do documento de visão, para ser aceita, é necessário que as 3 issues das quais esta issue é dependente sejam fechadas.
### Distribuição
Nesta issue consta 3 sub-issues que são requisitos de completude desta issue, onde, os membros designados para a tarefa devem se organizar na distribuição dos tópicos.
### Aceitação
Para ser aceita, as issues abaixo deverão estar completas
- [x] [Documento de Visão tópico 2: Posição ](https://github.com/fga-eps-mds/2019.1-PyLearner/issues/47)
- [x] [Documento de Visão tópico 4: Visão Geral do Produto ](https://github.com/fga-eps-mds/2019.1-PyLearner/issues/39)
- [x] [Documento de Visão tópico 5: Recursos do Produto](https://github.com/fga-eps-mds/2019.1-PyLearner/issues/40)
- [ ] [Documento de Visão tópico 6: Restrições](https://github.com/fga-eps-mds/2019.1-PyLearner/issues/41)

**Comment by gabrielziegler3** [comment]
@all-contributors please add @joao18araujo @alexportof @ZarathosDeath @Eugeniosales @Mexazonic  for docs
