### ISSUE TITLE
Task US02 - Criação dos Intents

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#89]
# Task US02 - Criação dos Intents
---
### Descrição:
Nesta issue o desenvolvedor deverá levantar os intents a serem utilizados na(o)s histórias/cenários do RASA. Respostas para todos os possíveis tópicos a respeito do tema devem ser levantadas, por exemplo, dúvidas sobre porque aquilo é utilizado ou como utilizar, devem ser respondidas. Os intents devem ser baseados na documentação levantada na task de estudo.

### Critérios de Aceitação
Para a aceitação da issue, os intents devem ter, no mínimo:
- [ ] 3 Respostas para cada major tópico 
- [ ] Responder dúvidas não funcionais que o usuário possa ter a respeito do tema
- [ ] Responder de forma detalhada assim como de forma sucinta, como utilizar aquela determinada funcionalidade

**Comment by Mexazonic** [comment]
Intents criadas e enviadas para revisão:
https://github.com/pylearner-bot/pylearner-rasa/blob/interacoes/bot/data/intents/interactions.md

**Comment by thiagoiferreira** [comment]
Pelo o que eu vi nesse link, estão apenas as intents das interações. Para o US02 são necessários os intents para importação de um JSON.

**Comment by Mexazonic** [comment]
<a href="https://github.com/pylearner-bot/pylearner-rasa/tree/US02-Importacao-Dados-JSON/bot/data/intents">Intents</a> prontas.
 <a href="https://github.com/pylearner-bot/pylearner-rasa/tree/US02-Importacao-Dados-JSON/bot">Templates e Actios</a> finalizados.
