### ISSUE TITLE
Task US04 - Criação dos Intents, actions e templates

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#90]
# Task US04 - Criação dos Intents, actions e templates
---
### Descrição:
Nesta issue o desenvolvedor deverá levantar os intents a serem utilizados na(o)s histórias/cenários do RASA. Respostas para todos os possíveis tópicos a respeito do tema devem ser levantadas, por exemplo, dúvidas sobre porque aquilo é utilizado ou como utilizar, devem ser respondidas. Os intents devem ser baseados na documentação levantada na task de estudo.

### Critérios de Aceitação
Para a aceitação da issue, os intents devem ter, no mínimo:
- [x] 3 Respostas para cada major tópico 
- [x] Responder dúvidas não funcionais que o usuário possa ter a respeito do tema
- [x] Responder de forma detalhada assim como de forma sucinta, como utilizar aquela determinada funcionalidade

**Comment by Eugeniosales** [comment]
Intents, actions e templates criados. [Intents](https://github.com/pylearner-bot/pylearner-rasa/blob/US-04-dados-faltantes/bot/data/intents/missing_data.md), [Templates e actions](https://github.com/pylearner-bot/pylearner-rasa/blob/US-04-dados-faltantes/bot/domain.yml)
