### ISSUE TITLE
EP01 - Importação de Dados

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#96]
# EP01 - Importação de Dados
---
### Descrição:
Este épico consiste nas tarefas relacionadas ao treinamento do bot no quesito importação de dados para machine learning, ensino ao bot inputs e outputs variados, relacionados ao tema.

Ao ser concluído, este épico disponibilizará no bot, possibilidade de tirar dúvidas sobre importação de dados para machine learning em, CSV, JSON e EXCEL.

### Histórias de Usuário
- [x] US01 - Eu como usuário desejo saber como importar dados de um arquivo CSV
- [x] US02 - Eu como usuário desejo saber como importar dados de um arquivo JSON
- [x] US03 - Eu como usuário desejo saber como importar dados de um arquivo EXCEL
