### ISSUE TITLE
EP02 - Tratamento de Dados

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#97]
# EP02 - Tratamento de Dados
---
### Descrição:
Este épico consiste nas tarefas relacionadas ao treinamento do bot no quesito tratamento de dados para machine learning, ensinando ao bot inputs e outputs variados, relacionados ao tema.

Ao ser concluído, este épico disponibilizará no bot, a possibilidade de tirar dúvidas sobre tratamento de dados para machine learning.

### Histórias de Usuário
- [x] US04 - Eu como usuário desejo saber como lidar com dados faltantes
- [ ] US05 - Eu como usuário desejo saber como transformar dados categóricos
- [ ] US06 - Eu como usuário desejo saber como lidar com dados com diferentes magnitudes
