### ISSUE TITLE
Task US01 - Histórias

### ISSUE THREAD

**Issue by thiagoiferreira** [fga-eps-mds/2019.1-PyLearner#99]
# Task US01 - Histórias
---
### Descrição:
Nessa task, necessária para completar a US01, o desenvolvedor deve criar as histórias para treinamento do chatbot.

### Critérios de Aceitação
- [ ] As histórias devem ser adequadas aos intents criados
- [ ] As histórias devem ser elaboradas em português
- [ ] As histórias devem responder as perguntas com a informação correta
